In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset=pd.read_csv("/content/drive/MyDrive/AAA_Dataset/diabetes dataset preprocessing.csv")

In [ ]:
dataset1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,D
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,N
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,D
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,N
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,D
...,...,...,...,...,...,...,...,...,...
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,N
768,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,D
769,10.0,115.0,0.0,0.0,0.0,35.3,0.134,29.0,N
770,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53.0,D
771,8.0,125.0,96.0,0.0,0.0,0.0,0.232,54.0,D

In [ ]:
#categorical
dataset1["Outcome"]=dataset1["Outcome"].apply(lambda e:0 if e=="N" else 1)

In [ ]:
dataset1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1
...,...,...,...,...,...,...,...,...,...
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0
768,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1
769,10.0,115.0,0.0,0.0,0.0,35.3,0.134,29.0,0
770,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53.0,1
771,8.0,125.0,96.0,0.0,0.0,0.0,0.232,54.0,1

In [ ]:
#x,y=dataset1.drop(["Outcome"],axis=1),dataset["Outcome"]

In [ ]:
# Check if there are any duplicates
dataset1.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
767    False
768     True
769     True
770     True
771     True
Length: 772, dtype: bool

In [ ]:
#removal
dataset1.drop_duplicates(inplace=True)
dataset1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,D
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,N
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,D
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,N
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,D
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,N
764,2.0,122.0,70.0,27.0,0.0,36.8,0.340,27.0,N
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,N
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,NaN,D
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,N

In [ ]:
# Check if there is any missing data
dataset1.isnull()

In [ ]:
# Fill missing data with 0
dataset1.fillna(0)

In [ ]:
# Or Drop entries with missing data
dataset1.dropna()

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer=SimpleImputer(missing_values=np.NaN, strategy='mean')
imputer.fit(dataset1["Age"].values.reshape(-1,1))

SimpleImputer()

In [ ]:
dataset1["Age"]=imputer.transform(dataset1["Age"].values.reshape(-1,1))

In [ ]:
imputer=SimpleImputer(missing_values=np.NaN, strategy='mean')
imputer.fit(dataset1["Glucose"].values.reshape(-1,1))
dataset1["Glucose"]=imputer.transform(dataset1["Glucose"].values.reshape(-1,1))

In [ ]:
imputer=SimpleImputer(missing_values=np.NaN, strategy='mean')
imputer.fit(dataset1["BloodPressure"].values.reshape(-1,1))
dataset1["BloodPressure"]=imputer.transform(dataset1["BloodPressure"].values.reshape(-1,1))

In [ ]:
imputer=SimpleImputer(missing_values=np.NaN, strategy='mean')
imputer.fit(dataset1["SkinThickness"].values.reshape(-1,1))
dataset1["SkinThickness"]=imputer.transform(dataset1["SkinThickness"].values.reshape(-1,1))

In [ ]:
imputer=SimpleImputer(missing_values=np.NaN, strategy='mean')
imputer.fit(dataset1["Insulin"].values.reshape(-1,1))
dataset1["Insulin"]=imputer.transform(dataset1["Insulin"].values.reshape(-1,1))

In [ ]:
imputer=SimpleImputer(missing_values=np.NaN, strategy='most_frequent')
imputer.fit(dataset1["Pregnancies"].values.reshape(-1,1))
dataset1["Pregnancies"]=imputer.transform(dataset1["Pregnancies"].values.reshape(-1,1))

In [ ]:
dataset1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.000000,D
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.000000,N
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.000000,D
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.000000,N
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.000000,D
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.000000,N
764,2.0,122.0,70.0,27.0,0.0,36.8,0.340,27.000000,N
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.000000,N
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,33.160105,D
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.000000,N

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [ ]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))